# Generated by Django 4.0.3 on 2022-04-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
